# -*- coding: utf-8 -*-
"""cp

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10gUekdmqJE99D3rQ3FGPIB2tQxQawiPS
"""

import sys, string, math, itertools

n = input()
n = int(n)
p = []

for i in range(0,n) :
    s = input()
    p.append(s)

common_prefix = []
for i in zip(*p):
    if i.count(i[0]) == len(i):
        common_prefix.append(i[0])
    else:
        break
ans = ''.join(common_prefix)
print(ans)