# -*- coding: utf-8 -*-
"""fivemultiples

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n7ocHd2eDpDhX6-pJjjQrNlQhad1AaAF
"""

n=int(input())
for i in range (1,6):
  print(n*i,end=" ")