# -*- coding: utf-8 -*-
"""romantoint

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pHKoA-9YPjn6f0qHYrquPvlOKwQJqlcM
"""

class py_solution:
    def roman_to_int(self, s):
        rom_val = {'I': 1, 'V': 5, 'X': 10, 'L': 50, 'C': 100, 'D': 500, 'M': 1000}
        int_val = 0
        for i in range(len(s)):
            if i > 0 and rom_val[s[i]] > rom_val[s[i - 1]]:
                int_val += rom_val[s[i]] - 2 * rom_val[s[i - 1]]
            else:
                int_val += rom_val[s[i]]
        return int_val
s=input()
ob=py_solution()
print(ob.roman_to_int(s))