# -*- coding: utf-8 -*-
"""swapnum

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13zlvoRaTwcfEGkkkToM1r31PbK_udf4I
"""

m,n=input().split()
t=0
t=m
m=n
n=t
print(m,n)