# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13zlvoRaTwcfEGkkkToM1r31PbK_udf4I
"""

n=int(input())
li=[]
inputarr=input()
li=inputarr.split()
li.sort()
inputarr=li
print(inputarr)